import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { Card, colors } from "@/components/xpense-ui";
import { trpc } from "@/lib/trpc";
import type { Category } from "@/lib/xpense-store";

export function AICoach({ spent, budget, categories, goalCount }: { spent: number; budget: number; categories: Record<Category, number>; goalCount: number }) {
  const [advice, setAdvice] = useState<{ headline: string; tips: string[]; action: string } | null>(null);
  const mutation = trpc.coach.advice.useMutation({ onSuccess: setAdvice });
  const getAdvice = () => mutation.mutate({ spent, budget, categories, goalCount });
  return <Card style={styles.card}><View style={styles.header}><View style={styles.icon}><MaterialIcons name="auto-awesome" size={21} color={colors.purple} /></View><View style={styles.copy}><Text style={styles.eyebrow}>AI COACH</Text><Text style={styles.title}>{advice?.headline ?? "Want a smarter money move?"}</Text></View></View>{advice ? <View style={styles.tips}>{advice.tips.map((tip, index) => <View key={`${tip}-${index}`} style={styles.tip}><Text style={styles.tipNumber}>{index + 1}</Text><Text style={styles.tipText}>{tip}</Text></View>)}<View style={styles.action}><Text style={styles.actionLabel}>TRY THIS</Text><Text style={styles.actionText}>{advice.action}</Text></View></View> : <Text style={styles.body}>Get three practical suggestions based on this month’s real spending and savings goals.</Text>}<Pressable onPress={getAdvice} disabled={mutation.isPending} style={({ pressed }) => [styles.button, pressed && { opacity: 0.7 }]}>{mutation.isPending ? <ActivityIndicator size="small" color="#fff" /> : <MaterialIcons name="psychology" size={17} color="#fff" />}<Text style={styles.buttonText}>{mutation.isPending ? "Thinking…" : advice ? "Refresh advice" : "Ask my coach"}</Text></Pressable>{mutation.error ? <Text style={styles.error}>Coach unavailable right now. Your local data is safe.</Text> : null}</Card>;
}

const styles = StyleSheet.create({ card: { padding: 16, marginBottom: 25, backgroundColor: "#FBF8FF", borderColor: "#E8DDFB" }, header: { flexDirection: "row", alignItems: "center" }, icon: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.purpleSoft, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, marginLeft: 10 }, eyebrow: { color: colors.purple, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, title: { color: colors.ink, fontSize: 14, fontWeight: "900", marginTop: 3 }, body: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 12 }, tips: { marginTop: 12 }, tip: { flexDirection: "row", alignItems: "flex-start", marginBottom: 8 }, tipNumber: { width: 20, height: 20, borderRadius: 10, backgroundColor: colors.purpleSoft, color: colors.purple, textAlign: "center", lineHeight: 20, fontSize: 10, fontWeight: "900" }, tipText: { color: colors.ink, flex: 1, fontSize: 11, lineHeight: 16, marginLeft: 8 }, action: { backgroundColor: "#fff", borderRadius: 12, padding: 10, marginTop: 3 }, actionLabel: { color: colors.purple, fontSize: 8, fontWeight: "900", letterSpacing: 1 }, actionText: { color: colors.ink, fontSize: 11, lineHeight: 16, marginTop: 3 }, button: { height: 42, borderRadius: 12, backgroundColor: colors.purple, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7, marginTop: 13 }, buttonText: { color: "#fff", fontSize: 12, fontWeight: "900" }, error: { color: colors.red, fontSize: 10, marginTop: 8 }, });
