import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { Card, colors, Currency, ProgressBar, SectionTitle } from "@/components/xpense-ui";
import { formatINR, useXPense, type Goal } from "@/lib/xpense-store";

export default function GoalsScreen() {
  const { goals, addToGoal, adjustGoal, createGoal } = useXPense();
  const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [addedGoal, setAddedGoal] = useState<string | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [newName, setNewName] = useState("");
  const [newTarget, setNewTarget] = useState("");
  const contribute = (goal: Goal) => { const amount = Number((amounts[goal.id] || "0").replace(/[^0-9.]/g, "")); if (amount <= 0) return; addToGoal(goal.id, amount); setAddedGoal(goal.id); setAmounts((current) => ({ ...current, [goal.id]: "" })); setTimeout(() => setAddedGoal(null), 1400); };
  const saveGoal = () => { const target = Number(newTarget.replace(/[^0-9.]/g, "")); if (!newName.trim() || target <= 0) return; createGoal({ name: newName.trim(), emoji: "🎯", target, dueLabel: "No due date", accent: colors.orange }); setNewName(""); setNewTarget(""); setShowNew(false); };
  return <ScreenContainer edges={["top", "left", "right"]} style={styles.screen}>
    <FlatList data={goals} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.topRow}><View><Text style={styles.pageTitle}>Goal vaults</Text><Text style={styles.subtitle}>Small deposits. Big milestones.</Text></View><Pressable onPress={() => setShowNew((current) => !current)} style={styles.addButton}><MaterialIcons name={showNew ? "close" : "add"} size={21} color="#fff" /></Pressable></View>{showNew ? <Card style={styles.newCard}><Text style={styles.newTitle}>Create a savings goal</Text><TextInput value={newName} onChangeText={setNewName} placeholder="Goal name" placeholderTextColor="#A7B2B9" style={styles.newInput} /><TextInput value={newTarget} onChangeText={setNewTarget} placeholder="Target amount in ₹" placeholderTextColor="#A7B2B9" keyboardType="decimal-pad" style={styles.newInput} /><Pressable onPress={saveGoal} style={styles.newButton}><Text style={styles.newButtonText}>Create goal</Text></Pressable></Card> : null}<Card dark style={styles.totalCard}><View><Text style={styles.darkLabel}>TOTAL SAVED</Text><Currency amount={goals.reduce((sum, goal) => sum + goal.saved, 0)} color="#fff" style={styles.totalAmount} /><Text style={styles.darkSmall}>across {goals.length} active vaults</Text></View><View style={styles.vaultIcon}><MaterialIcons name="savings" size={27} color={colors.yellow} /></View></Card><SectionTitle title="Your vaults" action="Flexible deposits" /></View>} renderItem={({ item }) => <GoalRow goal={item} amount={amounts[item.id] || ""} onAmount={(value) => setAmounts((current) => ({ ...current, [item.id]: value }))} onContribute={() => contribute(item)} onDecrease={() => adjustGoal(item.id, -Number((amounts[item.id] || "0").replace(/[^0-9.]/g, "")))} added={addedGoal === item.id} />} ListFooterComponent={<View style={styles.footer}><MaterialIcons name="lock-outline" size={17} color={colors.muted} /><Text style={styles.footerText}>Add, decrease, or create any vault amount. Saved locally and available offline.</Text></View>} />
  </ScreenContainer>;
}

function GoalRow({ goal, amount, onAmount, onContribute, onDecrease, added }: { goal: Goal; amount: string; onAmount: (value: string) => void; onContribute: () => void; onDecrease: () => void; added: boolean }) {
  const percent = Math.min(100, Math.round((goal.saved / goal.target) * 100));
  return <Card style={styles.goalCard}><View style={styles.goalHeader}><View style={styles.goalTitleRow}><Text style={styles.emoji}>{goal.emoji}</Text><View><Text style={styles.goalName}>{goal.name}</Text><Text style={styles.goalDue}>{goal.dueLabel}</Text></View></View><Text style={[styles.percent, { color: goal.accent }]}>{percent}%</Text></View><View style={styles.amountRow}><Currency amount={goal.saved} color={colors.ink} style={styles.saved} /><Text style={styles.target}>of {formatINR(goal.target)}</Text></View><ProgressBar value={goal.saved} total={goal.target} color={goal.accent} height={10} /><View style={styles.depositRow}><TextInput value={amount} onChangeText={onAmount} placeholder="Amount" placeholderTextColor="#A7B2B9" keyboardType="decimal-pad" style={styles.depositInput} /><Pressable onPress={onDecrease} style={[styles.smallButton, { borderColor: colors.red }]}><MaterialIcons name="remove" size={15} color={colors.red} /><Text style={[styles.smallButtonText, { color: colors.red }]}>Take out</Text></Pressable><Pressable onPress={onContribute} style={({ pressed }) => [styles.smallButton, { borderColor: goal.accent }, pressed && { opacity: 0.65 }]}><MaterialIcons name={added ? "check" : "add"} size={15} color={goal.accent} /><Text style={[styles.smallButtonText, { color: goal.accent }]}>{added ? "Added" : "Add"}</Text></Pressable></View><Text style={styles.toGo}>{formatINR(Math.max(goal.target - goal.saved, 0))} to go</Text></Card>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.canvas }, content: { padding: 20, paddingBottom: 35 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, pageTitle: { color: colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -0.8 }, subtitle: { color: colors.muted, fontSize: 13, marginTop: 4 }, addButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.orange, alignItems: "center", justifyContent: "center" }, newCard: { padding: 15, marginBottom: 15 }, newTitle: { color: colors.ink, fontSize: 14, fontWeight: "900", marginBottom: 8 }, newInput: { height: 44, borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 12, color: colors.ink, fontSize: 12, marginTop: 8 }, newButton: { height: 42, backgroundColor: colors.orange, borderRadius: 12, alignItems: "center", justifyContent: "center", marginTop: 10 }, newButtonText: { color: "#fff", fontSize: 12, fontWeight: "900" }, totalCard: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderRadius: 24, marginBottom: 25 }, darkLabel: { color: "#A4B7C3", fontSize: 10, letterSpacing: 1, fontWeight: "900" }, totalAmount: { fontSize: 28, marginTop: 9 }, darkSmall: { color: "#A4B7C3", fontSize: 11, marginTop: 3 }, vaultIcon: { width: 54, height: 54, borderRadius: 19, backgroundColor: "#493F2B", alignItems: "center", justifyContent: "center" }, goalCard: { marginBottom: 12, padding: 17 }, goalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, goalTitleRow: { flexDirection: "row", alignItems: "center", gap: 11 }, emoji: { fontSize: 28 }, goalName: { color: colors.ink, fontSize: 16, fontWeight: "900" }, goalDue: { color: colors.muted, fontSize: 11, marginTop: 3 }, percent: { fontSize: 16, fontWeight: "900" }, amountRow: { flexDirection: "row", alignItems: "baseline", marginTop: 18, marginBottom: 10, gap: 5 }, saved: { fontSize: 20 }, target: { color: colors.muted, fontSize: 12 }, depositRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 12 }, depositInput: { flex: 1, height: 36, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 9, color: colors.ink, fontSize: 11 }, smallButton: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 7, height: 36, flexDirection: "row", alignItems: "center", gap: 2 }, smallButtonText: { fontSize: 10, fontWeight: "800" }, toGo: { color: colors.muted, fontSize: 11, marginTop: 10 }, footer: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 5, marginTop: 20 }, footerText: { color: colors.muted, fontSize: 10, textAlign: "center", flex: 1 }, });
