import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { Card, colors, Currency, ProgressBar, SectionTitle } from "@/components/xpense-ui";
import { formatINR, useXPense, type Goal } from "@/lib/xpense-store";

export default function GoalsScreen() {
  const { goals, addToGoal } = useXPense();
  const [addedGoal, setAddedGoal] = useState<string | null>(null);
  const contribute = (goal: Goal) => { addToGoal(goal.id, 500); setAddedGoal(goal.id); setTimeout(() => setAddedGoal(null), 1400); };
  return <ScreenContainer edges={["top", "left", "right"]} style={styles.screen}>
    <FlatList data={goals} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.topRow}><View><Text style={styles.pageTitle}>Goal vaults</Text><Text style={styles.subtitle}>Small deposits. Big milestones.</Text></View><Pressable onPress={() => undefined} style={styles.addButton}><MaterialIcons name="add" size={21} color="#fff" /></Pressable></View><Card dark style={styles.totalCard}><View><Text style={styles.darkLabel}>TOTAL SAVED</Text><Currency amount={goals.reduce((sum, goal) => sum + goal.saved, 0)} color="#fff" style={styles.totalAmount} /><Text style={styles.darkSmall}>across {goals.length} active vaults</Text></View><View style={styles.vaultIcon}><MaterialIcons name="savings" size={27} color={colors.yellow} /></View></Card><SectionTitle title="Your vaults" action="Edit" onAction={() => undefined} /></View>} renderItem={({ item }) => <GoalRow goal={item} onContribute={() => contribute(item)} added={addedGoal === item.id} />} ListFooterComponent={<View style={styles.footer}><MaterialIcons name="lock-outline" size={17} color={colors.muted} /><Text style={styles.footerText}>Vaults are local-first and always available offline.</Text></View>} />
  </ScreenContainer>;
}

function GoalRow({ goal, onContribute, added }: { goal: Goal; onContribute: () => void; added: boolean }) {
  const percent = Math.round((goal.saved / goal.target) * 100);
  return <Card style={styles.goalCard}><View style={styles.goalHeader}><View style={styles.goalTitleRow}><Text style={styles.emoji}>{goal.emoji}</Text><View><Text style={styles.goalName}>{goal.name}</Text><Text style={styles.goalDue}>{goal.dueLabel}</Text></View></View><Text style={[styles.percent, { color: goal.accent }]}>{percent}%</Text></View><View style={styles.amountRow}><Currency amount={goal.saved} color={colors.ink} style={styles.saved} /><Text style={styles.target}>of {formatINR(goal.target)}</Text></View><ProgressBar value={goal.saved} total={goal.target} color={goal.accent} height={10} /><View style={styles.bottomRow}><Text style={styles.toGo}>{formatINR(Math.max(goal.target - goal.saved, 0))} to go</Text><Pressable onPress={onContribute} style={({ pressed }) => [styles.contribute, { borderColor: goal.accent }, pressed && { opacity: 0.65 }]}><MaterialIcons name={added ? "check" : "add"} size={15} color={goal.accent} /><Text style={[styles.contributeText, { color: goal.accent }]}>{added ? "Added ₹500" : "Add ₹500"}</Text></Pressable></View></Card>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.canvas }, content: { padding: 20, paddingBottom: 35 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, pageTitle: { color: colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -0.8 }, subtitle: { color: colors.muted, fontSize: 13, marginTop: 4 }, addButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.orange, alignItems: "center", justifyContent: "center" }, totalCard: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderRadius: 24, marginBottom: 25 }, darkLabel: { color: "#A4B7C3", fontSize: 10, letterSpacing: 1, fontWeight: "900" }, totalAmount: { fontSize: 28, marginTop: 9 }, darkSmall: { color: "#A4B7C3", fontSize: 11, marginTop: 3 }, vaultIcon: { width: 54, height: 54, borderRadius: 19, backgroundColor: "#493F2B", alignItems: "center", justifyContent: "center" }, goalCard: { marginBottom: 12, padding: 17 }, goalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, goalTitleRow: { flexDirection: "row", alignItems: "center", gap: 11 }, emoji: { fontSize: 28 }, goalName: { color: colors.ink, fontSize: 16, fontWeight: "900" }, goalDue: { color: colors.muted, fontSize: 11, marginTop: 3 }, percent: { fontSize: 16, fontWeight: "900" }, amountRow: { flexDirection: "row", alignItems: "baseline", marginTop: 18, marginBottom: 10, gap: 5 }, saved: { fontSize: 20 }, target: { color: colors.muted, fontSize: 12 }, bottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12 }, toGo: { color: colors.muted, fontSize: 11 }, contribute: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 9, paddingVertical: 7, flexDirection: "row", alignItems: "center", gap: 4 }, contributeText: { fontSize: 11, fontWeight: "800" }, footer: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 5, marginTop: 20 }, footerText: { color: colors.muted, fontSize: 10 }, });
