import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { Card, colors, LogoMark, MiniStat, SectionTitle } from "@/components/xpense-ui";
import { formatINR, useXPense } from "@/lib/xpense-store";

export default function ProfileScreen() {
  const { xp, coins, streak, transactions, goals } = useXPense();
  return <ScreenContainer edges={["top", "left", "right"]} style={styles.screen}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.topRow}><LogoMark /><Pressable onPress={() => router.push("/settings")} style={({ pressed }) => [styles.settingsButton, pressed && { opacity: 0.6 }]}><MaterialIcons name="settings" size={21} color={colors.ink} /></Pressable></View>
    <View style={styles.profileHead}><View style={styles.avatar}><Text style={styles.avatarText}>A</Text></View><Text style={styles.name}>Arjun Mehta</Text><Text style={styles.email}>arjun.mehta@campusmail.in</Text><View style={styles.levelPill}><MaterialIcons name="stars" size={15} color={colors.orange} /><Text style={styles.levelPillText}>Level 08 · Money learner</Text></View></View>
    <View style={styles.statsRow}><Card style={styles.statCard}><MiniStat label="Total XP" value={xp.toLocaleString("en-IN")} tint={colors.purple} /></Card><Card style={styles.statCard}><MiniStat label="Coins" value={coins.toLocaleString("en-IN")} tint={colors.yellow} /></Card><Card style={styles.statCard}><MiniStat label="Streak" value={`${streak} days`} tint={colors.orange} /></Card></View>
    <SectionTitle title="Your report card" action="This month" />
    <Card style={styles.reportCard}><View style={styles.gradeCircle}><Text style={styles.grade}>A−</Text><Text style={styles.gradeSmall}>great job</Text></View><View style={styles.reportCopy}><Text style={styles.reportTitle}>You’re building strong habits</Text><Text style={styles.reportBody}>You logged {transactions.length} expenses and have {goals.length} goals in motion. Keep your Food spend in check to protect your A.</Text><Pressable onPress={() => router.push("/activity")}><Text style={styles.reportLink}>View detailed insights →</Text></Pressable></View></Card>
    <SectionTitle title="Money setup" />
    <View style={styles.menu}><MenuRow icon="account-balance-wallet" title="Wallets" detail="UPI · Cash · Card" onPress={() => undefined} /><MenuRow icon="notifications-none" title="Nudges & alerts" detail="Smart reminders on" onPress={() => router.push("/settings")} /><MenuRow icon="groups" title="Squad mode" detail="Invite your roommates" onPress={() => undefined} /><MenuRow icon="school" title="Financial literacy" detail="12 lessons available" onPress={() => undefined} /></View>
    <Card style={styles.syncCard}><View style={styles.syncIcon}><MaterialIcons name="cloud-done" size={22} color={colors.teal} /></View><View style={styles.syncCopy}><Text style={styles.syncTitle}>Local-first & private</Text><Text style={styles.syncBody}>Your data is available offline. Cloud sync and squads can be connected when you’re ready.</Text></View></Card>
  </ScrollView></ScreenContainer>;
}

function MenuRow({ icon, title, detail, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.menuRow, pressed && { opacity: 0.62 }]}><View style={styles.menuIcon}><MaterialIcons name={icon} size={20} color={colors.orange} /></View><View style={styles.menuCopy}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDetail}>{detail}</Text></View><MaterialIcons name="chevron-right" size={21} color={colors.muted} /></Pressable>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.canvas }, content: { padding: 20, paddingBottom: 40 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, settingsButton: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, alignItems: "center", justifyContent: "center" }, profileHead: { alignItems: "center", paddingVertical: 24 }, avatar: { width: 78, height: 78, borderRadius: 30, backgroundColor: colors.orangeSoft, alignItems: "center", justifyContent: "center", borderWidth: 4, borderColor: "#fff" }, avatarText: { color: colors.orange, fontSize: 30, fontWeight: "900" }, name: { color: colors.ink, fontSize: 20, fontWeight: "900", marginTop: 12 }, email: { color: colors.muted, fontSize: 12, marginTop: 4 }, levelPill: { backgroundColor: colors.yellowSoft, borderRadius: 11, paddingHorizontal: 10, paddingVertical: 6, flexDirection: "row", alignItems: "center", gap: 4, marginTop: 10 }, levelPillText: { color: colors.ink, fontSize: 10, fontWeight: "800" }, statsRow: { flexDirection: "row", gap: 8, marginBottom: 25 }, statCard: { flex: 1, padding: 11, borderRadius: 16 }, reportCard: { flexDirection: "row", alignItems: "center", padding: 16, marginBottom: 25 }, gradeCircle: { width: 76, height: 76, borderRadius: 38, backgroundColor: colors.tealSoft, borderWidth: 7, borderColor: "#B6EDE4", alignItems: "center", justifyContent: "center" }, grade: { color: colors.teal, fontWeight: "900", fontSize: 24 }, gradeSmall: { color: colors.teal, fontSize: 8, fontWeight: "800", marginTop: -2 }, reportCopy: { flex: 1, paddingLeft: 14 }, reportTitle: { color: colors.ink, fontSize: 14, fontWeight: "900" }, reportBody: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5 }, reportLink: { color: colors.orange, fontSize: 11, fontWeight: "900", marginTop: 8 }, menu: { backgroundColor: colors.card, borderRadius: 19, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 14, marginBottom: 18 }, menuRow: { flexDirection: "row", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, menuIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.orangeSoft, alignItems: "center", justifyContent: "center" }, menuCopy: { flex: 1, marginLeft: 11 }, menuTitle: { color: colors.ink, fontSize: 13, fontWeight: "800" }, menuDetail: { color: colors.muted, fontSize: 10, marginTop: 3 }, syncCard: { flexDirection: "row", alignItems: "center", padding: 14 }, syncIcon: { width: 41, height: 41, borderRadius: 13, backgroundColor: colors.tealSoft, alignItems: "center", justifyContent: "center" }, syncCopy: { flex: 1, marginLeft: 11 }, syncTitle: { color: colors.ink, fontSize: 13, fontWeight: "900" }, syncBody: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, });
